[package]
name = "jpreprocess"
version = "0.1.2"
edition = "2021"

description = "Japanese text preprocessor for Text-to-Speech application (OpenJTalk rewrite in rust language)."
license = "BSD-3-Clause"
repository = "https://github.com/jpreprocess/jpreprocess"
keywords = ["tts", "openjtalk", "library"]
categories = ["text-processing"]
documentation = "https://docs.rs/jpreprocess"

[features]
naist-jdic=["jpreprocess-naist-jdic/naist-jdic"]

[dependencies]
lindera-core = { version = "0.25" }
lindera-tokenizer = { version = "0.25" }
lindera-dictionary = { version = "0.25" }
aho-corasick = "0.7"
once_cell = "1.17.0"
anyhow = "1.0.69"
unicode-jp = "0.4.0"

jpreprocess-core = { version = "0.1.1", path="../jpreprocess-core" }

jpreprocess-njd = { version = "0.1.1", path="../jpreprocess-njd" }
jpreprocess-jpcommon = { version = "0.1.1", path="../jpreprocess-jpcommon" }

jpreprocess-dictionary = { version = "0.1.1", path="../jpreprocess-dictionary" }

jpreprocess-naist-jdic = { version = "0.1.1", path="../jpreprocess-naist-jdic", optional = true }
